cool_places:list = ["Prague", "Usa", "France", "Stockolm", "Ireland"]
print(*cool_places)
cool_places_sorted:str = sorted(cool_places)
print(*cool_places_sorted)
print(*cool_places)
cool_places_sorted_backwards:str = sorted (cool_places, reverse=True)
print(*cool_places_sorted_backwards)
print(*cool_places)
cool_places.reverse()
print(*cool_places)
cool_places.reverse()
print(*cool_places)
cool_places.sort()
print(*cool_places)
cool_places.sort(reverse=True)
print(*cool_places)
